In [3]:
import argparse
import cv2
import numpy as np
import os
import torch
import pdb

from utils import setup_seed, read_points, read_calib, read_label, \
    keep_bbox_from_image_range, keep_bbox_from_lidar_range, vis_pc, \
    vis_img_3d, bbox3d2corners_camera, points_camera2image, \
    bbox_camera2lidar

In [4]:
def point_range_filter(pts, point_range=[0, -39.68, -3, 69.12, 39.68, 1]):
    '''
    data_dict: dict(pts, gt_bboxes_3d, gt_labels, gt_names, difficulty)
    point_range: [x1, y1, z1, x2, y2, z2]
    논문에 표기된 대로 car, pedstrian cyclist를 검출하는 포인터 범위
    '''
    flag_x_low = pts[:, 0] > point_range[0] # 0
    flag_y_low = pts[:, 1] > point_range[1] # -39.68
    flag_z_low = pts[:, 2] > point_range[2] # -3
    flag_x_high = pts[:, 0] < point_range[3] # 69.12
    flag_y_high = pts[:, 1] < point_range[4] # 39.68
    flag_z_high = pts[:, 2] < point_range[5] # 1
    keep_mask = flag_x_low & flag_y_low & flag_z_low & flag_x_high & flag_y_high & flag_z_high
    pts = pts[keep_mask]
    return pts 

In [5]:
import numpy as np
import pdb
import torch
import torch.nn as nn
import torch.nn.functional as F
from model.anchors import Anchors, anchor_target, anchors2bboxes
from ops import Voxelization, nms_cuda
from utils import limit_period


class PillarLayer(nn.Module):
    def __init__(self, voxel_size, point_cloud_range, max_num_points, max_voxels):
        super().__init__()
        self.voxel_layer = Voxelization(voxel_size=voxel_size,
                                        point_cloud_range=point_cloud_range,
                                        max_num_points=max_num_points,
                                        max_voxels=max_voxels)

    @torch.no_grad()
    def forward(self, batched_pts):
        '''
        batched_pts: list[tensor], len(batched_pts) = bs
        return: 
               pillars: (p1 + p2 + ... + pb, num_points, c), 
               coors_batch: (p1 + p2 + ... + pb, 1 + 3), 
               num_points_per_pillar: (p1 + p2 + ... + pb, ), (b: batch size)
        '''
        pillars, coors, npoints_per_pillar = [], [], []
        for i, pts in enumerate(batched_pts):
            voxels_out, coors_out, num_points_per_voxel_out = self.voxel_layer(pts) 
            # voxels_out: (max_voxel, num_points, c), coors_out: (max_voxel, 3)
            # num_points_per_voxel_out: (max_voxel, )
            pillars.append(voxels_out)
            coors.append(coors_out.long())
            npoints_per_pillar.append(num_points_per_voxel_out)
        
        pillars = torch.cat(pillars, dim=0) # (p1 + p2 + ... + pb, num_points, c)
        npoints_per_pillar = torch.cat(npoints_per_pillar, dim=0) # (p1 + p2 + ... + pb, )
        coors_batch = []
        for i, cur_coors in enumerate(coors):
            coors_batch.append(F.pad(cur_coors, (1, 0), value=i))
        coors_batch = torch.cat(coors_batch, dim=0) # (p1 + p2 + ... + pb, 1 + 3)

        return pillars, coors_batch, npoints_per_pillar


In [6]:
pc_folder_path = "dataset/testing/velodyne/"
pc_file_list = os.listdir(pc_folder_path)
pc = read_points(pc_folder_path + "/" + pc_file_list[0])

pc = point_range_filter(pc)
# pc_torch = torch.from_numpy(pc)

In [15]:
if __name__ == "__main__":

    # np.random.seed(22)

    device = torch.device("cuda:0")

    nclasses=3
    voxel_size=[0.16, 0.16, 0.16]
    point_cloud_range=[0, -39.68, -3, 69.12, 39.68, 1]
    max_num_points=32
    max_voxels=(16000, 40000)

    test_layer = PillarLayer(voxel_size=voxel_size,
                            point_cloud_range=point_cloud_range,
                            max_voxels=max_voxels,
                            max_num_points=max_num_points)

    # pc = np.random.uniform(-2, 8, size=[1000, 4]).astype(np.float32)
    pc_tensor = torch.from_numpy(pc).to(device)

    pillars, coors_batch, npoints_per_pillar = test_layer([pc_tensor])

    print(pillars.size())
    print(coors_batch.size())
    print(npoints_per_pillar.size())

    print(pillars[10])
    print(coors_batch[10])
    print(npoints_per_pillar[10])



torch.Size([16000, 32, 4])
torch.Size([16000, 4])
torch.Size([16000])
tensor([[20.3780,  4.6160,  0.9160,  0.3900],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 

In [13]:
pillars, coors_batch, npoints_per_pillar


(tensor([[[22.3920,  4.3760,  0.9810,  0.3800],
          [ 0.0000,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000]],
 
         [[22.4780,  4.4660,  0.9840,  0.2700],
          [ 0.0000,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000]],
 
         [[21.9480,  4.4320,  0.9660,  0.2100],
          [ 0.0000,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0000,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000]],
 
         ...,
 
         [[ 6.2280,  1.1360, -1.6530,  0.2700],
          [ 6.2220

In [8]:
vx, vy = voxel_size[0], voxel_size[1]
x_offset = voxel_size[0] / 2 + point_cloud_range[0]
y_offset = voxel_size[1] / 2 + point_cloud_range[1]

offset_pt_center = pillars[:, :, :3] - torch.sum(pillars[:, :, :3], dim=1, keepdim=True) / npoints_per_pillar[:, None, None] 
x_offset_pi_center = pillars[:, :, :1] - (coors_batch[:, None, 1:2] * vx + x_offset) # (p1 + p2 + ... + pb, num_points, 1)
y_offset_pi_center = pillars[:, :, 1:2] - (coors_batch[:, None, 2:3] * vy + y_offset) # (p1 + p2 + ... + pb, num_points, 1)


features = torch.cat([pillars, offset_pt_center, x_offset_pi_center, y_offset_pi_center], dim=-1) # (p1 + p2 + ... + pb, num_points, 9)
features[:, :, 0:1] = x_offset_pi_center # tmp
features[:, :, 1:2] = y_offset_pi_center # tmp

voxel_ids = torch.arange(0, pillars.size(1)).to(device) # (num_points, )
mask = voxel_ids[:, None] < npoints_per_pillar[None, :] # (num_points, p1 + p2 + ... + pb)
mask = mask.permute(1, 0).contiguous()  # (p1 + p2 + ... + pb, num_points)
features *= mask[:, :, None]




In [9]:
conv = nn.Conv1d(9, 64, 1, bias=False).to(device)
bn = nn.BatchNorm1d(64, eps=1e-3, momentum=0.01).to(device)
# 5. embedding
features = features.permute(0, 2, 1).contiguous()
features = F.relu(bn(conv(features)))  # (p1 + p2 + ... + pb, out_channels, num_points)
pooling_features = torch.max(features, dim=-1)[0] # (p1 + p2 + ... + pb, out_channels)




In [10]:
batched_canvas = []
bs = coors_batch[-1, 0] + 1

x_l = int((point_cloud_range[3] - point_cloud_range[0]) / voxel_size[0])
y_l = int((point_cloud_range[4] - point_cloud_range[1]) / voxel_size[1])

for i in range(bs):
    cur_coors_idx = coors_batch[:, 0] == i
    cur_coors = coors_batch[cur_coors_idx, :]
    cur_features = pooling_features[cur_coors_idx]
    print(cur_coors.size())
    canvas = torch.zeros((x_l, y_l, 64), dtype=torch.float32, device=device)
    canvas[cur_coors[:, 1], cur_coors[:, 2]] = cur_features

torch.Size([16000, 4])


In [11]:
cur_coors[0]

tensor([  0, 139, 275,  24], device='cuda:0')

In [12]:
pooling_features.size()

torch.Size([16000, 64])

In [160]:
bs

tensor(1, device='cuda:0')

In [164]:
coors_batch[-1][0]

tensor(0, device='cuda:0')

In [175]:
torch.zeros(2,3,4).size()

torch.Size([2, 3, 4])